[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:admin"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/public-test-kv"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "tara-hub-api"
type = "web"

[[services.domains]]
domain = "${RAILWAY_STATIC_URL}"

[[services.domains]]
domain = "tara-hub-api.railway.app"