import { kv } from './kv'
import { type Fabric } from './types'

export const fabricSeedData: Fabric[] = [
  {
    id: 'natural-linen-001',
    name: 'Natural Linen Blend',
    description:
      'A luxurious blend of natural linen and cotton, perfect for upholstery and drapery. Features a beautiful natural texture with excellent breathability.',
    category: 'Natural Fibers',
    color: 'Natural',
    composition: '55% Linen, 45% Cotton',
    width: '54 inches',
    weight: '12 oz/sq yd',
    durability: 'Heavy Duty',
    careInstructions: 'Dry clean only',
    inStock: true,
    swatchImageUrl: '/natural-linen-fabric.png',
    detailImages: [
      '/natural-linen-fabric.png',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: ['Upholstery', 'Drapery', 'Cushions', 'Headboards'],
    features: [
      'Natural texture',
      'Breathable',
      'Eco-friendly',
      'Wrinkle-resistant finish',
    ],
    origin: 'Belgium',
    designer: 'European Mills',
    collection: 'Natural Elements',
    patternRepeat: 'N/A - Solid',
    flammabilityRating: 'Cal TB 117-2013',
    abrasionRating: '50,000 double rubs',
    lightFastness: 'Grade 4-5',
    pillResistance: 'Grade 4',
  },
  {
    id: 'emerald-velvet-002',
    name: 'Emerald Green Velvet',
    description:
      'Rich emerald green velvet with a lustrous finish. This premium fabric offers exceptional depth of color and luxurious hand feel.',
    category: 'Velvet',
    color: 'Green',
    composition: '100% Cotton Velvet',
    width: '54 inches',
    weight: '16 oz/sq yd',
    durability: 'Medium Duty',
    careInstructions: 'Professional cleaning recommended',
    inStock: true,
    swatchImageUrl: '/emerald-green-velvet.png',
    detailImages: [
      '/emerald-green-velvet.png',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: ['Accent chairs', 'Pillows', 'Drapery', 'Ottomans'],
    features: [
      'Rich color depth',
      'Soft hand',
      'Light-reflective',
      'Stain-resistant treatment',
    ],
    origin: 'Italy',
    designer: 'Milano Textiles',
    collection: 'Jewel Tones',
    patternRepeat: 'N/A - Solid',
    flammabilityRating: 'NFPA 260',
    abrasionRating: '25,000 double rubs',
    lightFastness: 'Grade 4',
    pillResistance: 'Grade 3',
  },
  {
    id: 'geometric-jacquard-003',
    name: 'Modern Geometric Jacquard',
    description:
      'Contemporary geometric pattern in neutral tones. Woven jacquard construction provides durability and visual interest.',
    category: 'Jacquard',
    color: 'Multi',
    composition: '60% Polyester, 40% Cotton',
    width: '56 inches',
    weight: '14 oz/sq yd',
    durability: 'Heavy Duty',
    careInstructions: 'Machine washable, gentle cycle',
    inStock: false,
    swatchImageUrl:
      '/placeholder.svg?height=300&width=300',
    detailImages: [
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: ['Sofas', 'Chairs', 'Panels', 'Commercial spaces'],
    features: ['Geometric design', 'Fade-resistant', 'Easy care', 'Contract grade'],
    origin: 'USA',
    designer: 'Contemporary Designs',
    collection: 'Urban Living',
    patternRepeat: '12 inches horizontal, 8 inches vertical',
    flammabilityRating: 'Cal TB 117-2013',
    abrasionRating: '100,000 double rubs',
    lightFastness: 'Grade 5',
    pillResistance: 'Grade 4-5',
  },
  {
    id: 'silk-damask-004',
    name: 'Ivory Silk Damask',
    description:
      'Elegant ivory silk damask with traditional floral motifs. Perfect for formal settings and luxury applications.',
    category: 'Silk',
    color: 'Ivory',
    composition: '100% Silk',
    width: '50 inches',
    weight: '10 oz/sq yd',
    durability: 'Light Duty',
    careInstructions: 'Dry clean only',
    inStock: true,
    swatchImageUrl: '/placeholder.svg?height=300&width=300',
    detailImages: [
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: ['Drapery', 'Formal upholstery', 'Decorative panels', 'Bedding'],
    features: [
      'Natural silk luster',
      'Traditional pattern',
      'Luxurious feel',
      'Hypoallergenic',
    ],
    origin: 'China',
    designer: 'Heritage Silks',
    collection: 'Classic Elegance',
    patternRepeat: '18 inches horizontal, 24 inches vertical',
    flammabilityRating: 'NFPA 701',
    lightFastness: 'Grade 3-4',
    pillResistance: 'Grade 2',
  },
  {
    id: 'outdoor-solution-005',
    name: 'Weather-Resistant Solution Dyed',
    description:
      'High-performance outdoor fabric with solution-dyed acrylic fibers. Excellent fade and weather resistance.',
    category: 'Outdoor',
    color: 'Navy',
    composition: '100% Solution-Dyed Acrylic',
    width: '60 inches',
    weight: '9 oz/sq yd',
    durability: 'Heavy Duty',
    careInstructions: 'Machine washable or hose clean',
    inStock: true,
    swatchImageUrl: '/placeholder.svg?height=300&width=300',
    detailImages: [
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: [
      'Outdoor furniture',
      'Awnings',
      'Marine upholstery',
      'Patio cushions',
    ],
    features: [
      'UV resistant',
      'Water repellent',
      'Mildew resistant',
      'Easy cleaning',
    ],
    origin: 'USA',
    designer: 'Outdoor Living Co.',
    collection: 'All-Weather',
    patternRepeat: 'N/A - Solid',
    flammabilityRating: 'NFPA 260',
    abrasionRating: '40,000 double rubs',
    lightFastness: 'Grade 5',
    pillResistance: 'Grade 4',
  },
  {
    id: 'mohair-blend-006',
    name: 'Luxury Mohair Blend',
    description:
      'Premium mohair blend with exceptional durability and natural luster. Ideal for high-end residential and hospitality projects.',
    category: 'Mohair',
    color: 'Charcoal',
    composition: '70% Mohair, 30% Wool',
    width: '52 inches',
    weight: '18 oz/sq yd',
    durability: 'Heavy Duty',
    careInstructions: 'Professional cleaning only',
    inStock: false,
    swatchImageUrl: '/placeholder.svg?height=300&width=300',
    detailImages: [
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: [
      'Executive seating',
      'Hospitality',
      'Residential upholstery',
      'Accent pieces',
    ],
    features: [
      'Natural luster',
      'Exceptional durability',
      'Soil resistant',
      'Flame retardant',
    ],
    origin: 'South Africa',
    designer: 'Premium Textiles',
    collection: 'Executive Collection',
    patternRepeat: 'N/A - Solid',
    flammabilityRating: 'Cal TB 117-2013',
    abrasionRating: '200,000 double rubs',
    lightFastness: 'Grade 4-5',
    pillResistance: 'Grade 5',
  },
  {
    id: 'botanical-print-007',
    name: 'Botanical Print Linen',
    description:
      'Hand-drawn botanical print on premium linen base. Features detailed leaf and flower motifs in soft, natural colors.',
    category: 'Printed',
    color: 'Multi',
    composition: '100% Linen',
    width: '54 inches',
    weight: '11 oz/sq yd',
    durability: 'Medium Duty',
    careInstructions: 'Dry clean recommended',
    inStock: true,
    swatchImageUrl: '/placeholder.svg?height=300&width=300',
    detailImages: [
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: ['Drapery', 'Accent chairs', 'Pillows', 'Wall panels'],
    features: [
      'Hand-drawn design',
      'Natural dyes',
      'Eco-friendly',
      'Unique pattern',
    ],
    origin: 'France',
    designer: 'Atelier Botanique',
    collection: 'Garden Collection',
    patternRepeat: '25 inches horizontal, 27 inches vertical',
    flammabilityRating: 'NFPA 260',
    abrasionRating: '30,000 double rubs',
    lightFastness: 'Grade 4',
    pillResistance: 'Grade 3',
  },
  {
    id: 'performance-microfiber-008',
    name: 'Performance Microfiber',
    description:
      'Advanced microfiber technology provides superior stain resistance and easy maintenance. Perfect for family-friendly applications.',
    category: 'Performance',
    color: 'Taupe',
    composition: '100% Polyester Microfiber',
    width: '58 inches',
    weight: '13 oz/sq yd',
    durability: 'Heavy Duty',
    careInstructions: 'Machine washable, tumble dry low',
    inStock: true,
    swatchImageUrl:
      '/placeholder.svg?height=300&width=300',
    detailImages: [
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
      '/placeholder.svg?height=400&width=400',
    ],
    applications: [
      'Family room furniture',
      'Dining chairs',
      'Commercial seating',
      'Healthcare',
    ],
    features: ['Stain resistant', 'Easy care', 'Soft hand', 'Antimicrobial'],
    origin: 'USA',
    designer: 'Tech Textiles',
    collection: 'Family Living',
    patternRepeat: 'N/A - Solid',
    flammabilityRating: 'Cal TB 117-2013',
    abrasionRating: '75,000 double rubs',
    lightFastness: 'Grade 5',
    pillResistance: 'Grade 4',
  },
]

export async function seedFabrics() {
  console.log('Seeding fabrics...')
  await Promise.all(
    fabricSeedData.map(async (fabric) => {
      const key = `fabric:${fabric.id}`
      await kv.hset(key, fabric)
    })
  )
  console.log(`Seeded ${fabricSeedData.length} fabrics.`)
}
