[providers]
node = "18"

[variables]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "development"

[phases.build]
cmds = [
  "npm ci --include=dev",
  "npx medusa build",
  "mkdir -p .medusa/server/public/admin",
  "if [ -d '.medusa/admin' ]; then cp -r .medusa/admin/* .medusa/server/public/admin/ || echo 'Copy failed, continuing...'; fi",
  "ln -sf .medusa/server/public/ public",
  "cd .medusa/server && npm ci"
]

[phases.start]
cmd = "cd .medusa/server && npm run predeploy && npm start"