[build]
builder = "nixpacks"

[build.nixpacksConfigPath]
configPath = "./nixpacks.toml"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10